### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Haiz14** [Chuvi-w/DynPatcher#1]
Sorry, to send message here, but how can I contact u ?

**Comment by Chuvi-w** [comment]
What is the purpose of contact with me? For what?

**Comment by Haiz14** [comment]
``fatal error: 'android_lf.h' file not found``

I faced this error while doing ``pip install cmake`` u seem to have solved this issue  https://gitlab.kitware.com/cmake/cmake/-/issues/21399 

So, i wanted to ask if u could plss help me. The above issue tellse to change some settings but i am not able to understand how to change it. https://github.com/termux/termux-packages/issues/10065

**Comment by Chuvi-w** [comment]
Huh. It somehow solves itself.
I
Hm. Wait. Try to look at termux packages. maybe you'll find some userful patch there.

https://github.com/termux/termux-packages/tree/master/packages/cmake

**Comment by Haiz14** [comment]
Yupp solved.
